{
 "title": "NGINX exporter",
 "description": "metrics obtained from NGINX basic",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(nginx_up,host)" } }
  ]
 },
 "panels": [
  {
   "title": "NGINX status",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{host=~\"$host\"}",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Connections rates over 2 min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted{host=~\"$host\"}[2m])",
     "legendFormat": "{{host}} active"
    },
    {
     "expr": "rate(nginx_connections_handled{host=~\"$host\"}[2m])",
     "legendFormat": "{{host}} handled"
    },
    {
     "expr": "rate(nginx_http_requests_total{host=~\"$host\"}[2m])",
     "legendFormat": "{{host}} total"
    }
   ]
  },
  {
   "title": "Current Connections count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nginx_connections_active{host=~\"$host\"}",
     "legendFormat": "{{host}} active"
    },
    {
     "expr": "nginx_connections_reading{host=~\"$host\"}",
     "legendFormat": "{{host}} reading"
    },
    {
     "expr": "nginx_connections_writing{host=~\"$host\"}",
     "legendFormat": "{{host}} writing"
    },
    {
     "expr": "nginx_connections_waiting{host=~\"$host\"}",
     "legendFormat": "{{host}} waiting"
    }
   ]
  }
 ]
}