# Global defaults.
global:
  # max timeout for the exporter: if prometheus sends a value greater than scrape_timeout, scrape_timeout will be used
  scrape_timeout: 30s
  # Subtracted from Prometheus' scrape_timeout to give us some headroom and prevent Prometheus from timing out first.
  scrape_timeout_offset: 500ms
  # Minimum interval between collector runs: by default (0s) collectors are executed on every scrape.
  min_interval: 0s
  # all unsuccessful queries will be retried this number of times
  query_retry: 3
  # all metrics will be named "[metric_prefix]_[metric_name]"
  metric_prefix: "veeam_em"
  # all http codes that will consider the connection has an invalid auth and must do a Login()
  invalid_auth_code: [401,403]
  exporter_name: veeam_exporter

profiles_file_config:
  - "profiles/*_profile.yml"

# list of authentication configuration to use to access to a target.
auth_configs:
  prometheus_encrypted:
    mode: script
    user: prometheus
    password: "/encrypted/__________XXXXXXX_______________XXXXXXX_______"

# The targets to monitor and the collectors to execute on it.
targets:
  # default target is used as a pattern for exporter queries with target name not defined locally.
  - name: default
    scheme: https
    host: template
    port: 9398
    auth_name: prometheus_encrypted
    # auth_config:
    #   # mode: basic|token|[anything else:=> user defined login script]
    #   mode: script
    #   user: usrVeeam
    #   password: "/encrypted/base64_encrypted_password_by_passwd_crypt_cmd"
    profile: veeam
    collectors:
      - ~.*_metrics

  - targets_files: [ "/etc/httpapi_exporter/veeam/targets/*.yml" ]

# Collector files specifies a list of globs. One collector definition is read from each matching file.
collector_files:
  - "metrics/*.collector.yml"

