{
 "title": "Veeam Enterprise Manager",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "enterprisemanager",
    "label": "Enterprise Manager",
    "query": {
     "query": "label_values(veeam_em_up, instance)"
    }
   },
   {
    "name": "backupserver",
    "query": {
     "query": "label_values(veeam_em_backup_servers_config, name)"
    }
   },
   {
    "name": "backupserver_version",
    "label": "BackupServer Version",
    "query": {
     "query": "label_values(veeam_em_backup_servers_config{name=~\"$backupserver\"},version)"
    }
   },
   {
    "name": "vm_status",
    "label": "VM BackupJob Status",
    "query": "Undefined : 0, Success : 1,   Warning : 2, Failed : 3, Pending -Idle : 4 , Working-In Progress : 5"
   }
  ]
 },
 "panels": [
  { "title": "Enterprise Manager - Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backup Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "veeam_em_overview_element_count{instance=~\"$enterprisemanager\", count_type=\"server\", type=\"backup\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Repository Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "veeam_em_overview_element_count{instance=~\"$enterprisemanager\", count_type=\"server\", type=\"repository\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Proxy Servers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "veeam_em_overview_element_count{instance=~\"$enterprisemanager\", count_type=\"server\", type=\"proxy\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Scueduled Jobs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "veeam_em_overview_element_count{instance=~\"$enterprisemanager\", count_type=\"tasks\", type=\"scheduled_jobs\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Total Source VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "veeam_em_overview_vms_total_bytes{instance=~\"$enterprisemanager\", type=\"source_vms\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Full backup VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "veeam_em_overview_vms_total_bytes{instance=~\"$enterprisemanager\", type=\"full_backup_points\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Successful VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "veeam_em_overview_element_count{instance=~\"$enterprisemanager\", count_type=\"tasks\", type=\"successful_vms\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Warning VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "veeam_em_overview_element_count{instance=~\"$enterprisemanager\", count_type=\"tasks\", type=\"warning_vms\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Failed VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "veeam_em_overview_element_count{instance=~\"$enterprisemanager\", count_type=\"tasks\", type=\"failed_vms\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Protected VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "veeam_em_overview_vms_count{instance=~\"$enterprisemanager\", type=\"protected\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Incremental backup VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "veeam_em_overview_vms_total_bytes{instance=~\"$enterprisemanager\", type=\"incremental_backup_points\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Replica Restore VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "veeam_em_overview_vms_total_bytes{instance=~\"$enterprisemanager\", type=\"replica_restore_points\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backup Repository - Usage Capacity",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - (sum(veeam_em_overview_repositories_capacity_free_bytes{}) by (name, type) / sum(veeam_em_overview_repositories_capacity_total_bytes{}) by (name, type) )",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "sum(veeam_em_overview_repositories_capacity_total_bytes{}) by (name, type)"
      },
      {
       "expr": "sum(veeam_em_overview_repositories_capacity_free_bytes{}) by (name, type)"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Historical Performance and Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "Backup Job State (last 24 hours)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(veeam_em_jobs_sessions_state{instance=~\"$enterprisemanager\"} == 1) or vector(0)",
     "legendFormat": "Success"
    },
    {
     "expr": "count(veeam_em_jobs_sessions_state{instance=~\"$enterprisemanager\"} == 2) or vector(0)",
     "legendFormat": "Warning"
    },
    {
     "expr": "count(veeam_em_jobs_sessions_state{instance=~\"$enterprisemanager\"} == 3) or vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(veeam_em_jobs_sessions_state{instance=~\"$enterprisemanager\"} == 4) or vector(0)",
     "legendFormat": "Idle"
    },
    {
     "expr": "count(veeam_em_jobs_sessions_state{instance=~\"$enterprisemanager\"} == 5) or vector(0)",
     "legendFormat": "Working"
    }
   ]
  },
  {
   "title": "Backup VM Jobs State  (last 24 hours)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(veeam_em_vmjobs_sessions_state{instance=~\"$enterprisemanager\"} == 1) or vector(0)",
     "legendFormat": "Success"
    },
    {
     "expr": "count(veeam_em_vmjobs_sessions_state{instance=~\"$enterprisemanager\"} == 2) or vector(0)",
     "legendFormat": "Warning"
    },
    {
     "expr": "count(veeam_em_vmjobs_sessions_state{instance=~\"$enterprisemanager\"} == 3) or vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(veeam_em_jobs_sessions_state{instance=~\"$enterprisemanager\"} == 4) or vector(0)",
     "legendFormat": "Idle"
    },
    {
     "expr": "count(veeam_em_jobs_sessions_state{instance=~\"$enterprisemanager\"} == 5) or vector(0)",
     "legendFormat": "Working"
    }
   ]
  },
  {
   "title": "Backup Job Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "veeam_em_jobs_sessions_state{instance=~\"$enterprisemanager\"}"
    },
    {
     "expr": "veeam_em_jobs_sessions_duration{instance=~\"$enterprisemanager\"}"
    },
    {
     "expr": "veeam_em_jobs_sessions_retries{instance=~\"$enterprisemanager\"}"
    }
   ]
  },
  {
   "title": "Backup VMJob Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "veeam_em_vmjobs_sessions_state{instance=~\"$enterprisemanager\"}"
    },
    {
     "expr": "veeam_em_vmjobs_sessions_duration{instance=~\"$enterprisemanager\"}"
    },
    {
     "expr": "veeam_em_vmjobs_sessions_total_bytes{instance=~\"$enterprisemanager\"}"
    }
   ]
  },
  {
   "title": "Backup VMJob Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "veeam_em_vmjobs_sessions_error{instance=~\"$enterprisemanager\"}"
    }
   ]
  },
  {
   "title": "Job Duration (All type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "veeam_em_overview_jobs_max_duration{instance=~\"$enterprisemanager\"}",
     "legendFormat": "MAX {{ jobname }} ( {{ type }} )"
    },
    {
     "expr": "avg(veeam_em_jobs_sessions_duration{instance=~\"$enterprisemanager\"}) by(backupserver)",
     "legendFormat": "avg {{ backupserver }} "
    }
   ]
  },
  {
   "title": "Job Reries percent (All type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (count (veeam_em_jobs_sessions_retries{instance=~\"$enterprisemanager\"} != 0 ) by(instance, backupserver)/ count(veeam_em_jobs_sessions_retries{instance=~\"$enterprisemanager\"} ) by(instance, backupserver) )",
     "legendFormat": "{{ backupserver }}"
    }
   ]
  },
  {
   "title": "backup Jobs for [$backupserver]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "repeat": "backupserver"
  },
  {
   "title": "Job State",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(veeam_em_jobs_sessions_state{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"} == 1) or vector(0)",
     "legendFormat": "Success"
    },
    {
     "expr": "count(veeam_em_jobs_sessions_state{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"} == 2) or vector(0)",
     "legendFormat": "Warning"
    },
    {
     "expr": "count(veeam_em_jobs_sessions_state{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"} == 3) or vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(veeam_em_jobs_sessions_state{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"} == 4) or vector(0)",
     "legendFormat": "Idle"
    },
    {
     "expr": "count(veeam_em_jobs_sessions_state{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"} == 5) or vector(0)",
     "legendFormat": "Working"
    }
   ]
  },
  {
   "title": "Backup Job Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 56 },
   "targets": [
    {
     "expr": "veeam_em_jobs_sessions_state{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"}"
    },
    {
     "expr": "veeam_em_jobs_sessions_duration{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"}"
    },
    {
     "expr": "veeam_em_jobs_sessions_retries{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"}"
    }
   ]
  },
  {
   "title": "VM Jobs State",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(veeam_em_vmjobs_sessions_state{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"} == 1) or vector(0)",
     "legendFormat": "Success"
    },
    {
     "expr": "count(veeam_em_vmjobs_sessions_state{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"} == 2) or vector(0)",
     "legendFormat": "Warning"
    },
    {
     "expr": "count(veeam_em_vmjobs_sessions_state{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"} == 3) or vector(0)",
     "legendFormat": "Failed"
    },
    {
     "expr": "count(veeam_em_vmjobs_sessions_state{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"} == 4) or vector(0)",
     "legendFormat": "Idle"
    },
    {
     "expr": "count(veeam_em_vmjobs_sessions_state{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"} == 5) or vector(0)",
     "legendFormat": "Working"
    }
   ]
  },
  {
   "title": "Backup VMJob Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 65 },
   "targets": [
    {
     "expr": "veeam_em_vmjobs_sessions_state{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"}"
    },
    {
     "expr": "veeam_em_vmjobs_sessions_duration{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"}"
    },
    {
     "expr": "veeam_em_vmjobs_sessions_retries{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"}"
    },
    {
     "expr": "veeam_em_vmjobs_sessions_total_bytes{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"}"
    }
   ]
  },
  {
   "title": "VM Backup Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "veeam_em_vmjobs_sessions_error{instance=~\"$enterprisemanager\", backupserver=~\"$backupserver\"}"
    }
   ]
  },
  {
   "title": "Veeam Agent Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 325 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backup Agent Status",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "veeam_em_agents_status{instance=~\"$enterprisemanager\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup Server Performance [ $backupserver ( $backupserver_version )]  (node_exporter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 326 },
   "collapsed": true,
   "panels": [
    {
     "title": "Description",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 0, "y": 149 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "veeam_em_backup_servers_config{instance=~\"$enterprisemanager\", name=~\"$backupserver\"}"
      }
     ]
    },
    {
     "title": "Description",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 7, "y": 149 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "veeam_em_backup_servers_config{instance=~\"$enterprisemanager\", name=~\"$backupserver\"}"
      }
     ]
    },
    {
     "title": "Port",
     "type": "stat",
     "gridPos": { "h": 3, "w": 7, "x": 14, "y": 149 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "veeam_em_backup_servers_config{instance=~\"$enterprisemanager\", name=~\"$backupserver\"}"
      }
     ]
    },
    {
     "title": "CPU Usage / $backupserver",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 152 },
     "repeat": "backupserver",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "1 - (sum by (host) (rate(windows_cpu_time_total{host=\"$backupserver\", mode=\"idle\"}[5m])) / count by (host) (windows_cpu_core_frequency_mhz{host=\"$backupserver\"}) )",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Memory / $backupserver",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 168 },
     "repeat": "backupserver",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "windows_os_virtual_memory_bytes{host=~\"$backupserver\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Virtual memory {{ host }}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "windows_cs_physical_memory_bytes{host=~\"$backupserver\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Physical memory  {{ host }}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "windows_os_physical_memory_free_bytes{host=~\"$backupserver\"}",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Free physical memory  {{ host }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Satus $backupserver",
     "type": "stat",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 184 },
     "repeat": "backupserver",
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "up{host=~\"$backupserver\"}",
       "legendFormat": "{{ host }}"
      }
     ]
    },
    {
     "title": "Disks $backupserver",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 192 },
     "repeat": "backupserver",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "100 - (windows_logical_disk_free_bytes{host=~\"$backupserver\"} / windows_logical_disk_size_bytes{host=~\"$backupserver\"})*100",
       "legendFormat": "{{ volume }}"
      }
     ]
    },
    {
     "title": "Network $backupserver",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 206 },
     "repeat": "backupserver",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "rate(windows_net_bytes_sent_total{host=~\"$backupserver\"}[5m]) >0",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Sent {{nic}} {{ host }}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "rate(windows_net_bytes_received_total{host=~\"$backupserver\"}[5m]) <0",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Received {{nic}} {{ host }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  }
 ]
}