- targets: [ "nginx_node_1:9117" ]
  labels:
    # the target itself using nginx_exporter default template
    __param_target: "http://nginx_node_1:8080"
    # if you have activated password encrypted passphrass
    # __param_auth_key: __shared__auth_passphrase__
    # or use a custom template call my_template
    #__param_model: my_template
    host: "nginx_node_1:8080"
    #custom labels…
    application: "NGINX"
    environment: "DEV"
