{
 "title": "ARUBA Hardware",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "application",
    "query": {
     "query": "label_values(up{job=~\"arubacx.*\"},application)"
    }
   },
   {
    "name": "site",
    "query": {
     "query": "label_values(up{job=~\"arubacx.*\",  application=~\"$application\"},site)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(up{job=~\"arubacx.*\",  application=~\"$application\"},group)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(up{job=~\"arubacx.*\",  application=~\"$application\", group=~\"$group\", site=~\"$site\"},host)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=~\"arubacx.*\",  application=~\"$application\", group=~\"$group\", site=~\"$site\", host=~\"$host\"},instance)"
    }
   },
   {
    "name": "show_hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(up{job=~\"arubacx.*\",  application=~\"$application\", group=~\"$group\", site=~\"$site\", instance=~\"$instance\"},host)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(arubacx_if_admin_status{job=~\"arubacx.*\",  application=~\"$application\", group=~\"$group\", site=~\"$site\", host=~\"$host\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General Infos - Site [$site] - Group [$group]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Host Response overwiew Site [ $site] - Group [ $group ]",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(arubacx_up{job=~\"arubacx_.*\", application=~\"$application\", site=~\"$site\", group=~\"$group\"}) by (host, group, site, application, segment, environment,instance)"
    },
    {
     "expr": "time() \r\n- sum  by (host, group, site, application, segment, environment, instance) (arubacx_system_boot_time {site=~\"$site\", group=~\"$group\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum  by (host, group, site, application, segment, environment, instance) (arubacx_system_boot_time{site=~\"$site\", group=~\"$group\"}*1000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n  count (\r\n    # not (ok:1 and empty:2)\r\n    arubacx_fans_status{site=~\"$site\", group=~\"$group\"} == 0\r\n  ) by (host, group, site, application, segment, environment,instance) \r\n)\r\nor 0 * (\r\n  count ( \r\n    arubacx_fans_status{site=~\"$site\", group=~\"$group\"} == 1\r\n  ) by (host, group, site, application, segment, environment,instance)\r\n)"
    },
    {
     "expr": "(\r\n  count (\r\n    arubacx_ps_status{site=~\"$site\", group=~\"$group\"} == 0\r\n  ) by (host, group, site, application, segment, environment,instance)\r\n)\r\nor\r\n(\r\n  0 *   count ( \r\n    arubacx_ps_status{site=~\"$site\", group=~\"$group\"} == 1\r\n  ) by (host, group, site, application, segment, environment,instance)\r\n)"
    },
    {
     "expr": "sum (\r\n    arubacx_system_cpu_usage_percent{site=~\"$site\", group=~\"$group\"}\r\n  ) by (host, group, site, application, segment, environment,instance)"
    },
    {
     "expr": "sum (\r\n    arubacx_system_memory_usage_percent {site=~\"$site\", group=~\"$group\"}\r\n  ) by (host, group, site, application, segment, environment,instance)"
    },
    {
     "expr": "avg (\r\n    rate(arubacx_if_in_bytes{site=~\"$site\", group=~\"$group\"}[5m]) * 8\r\n  ) by (host, group, site, application, segment, environment,instance)"
    },
    {
     "expr": "avg (\r\n    rate(arubacx_if_out_bytes{site=~\"$site\", group=~\"$group\"}[5m]) * 8\r\n  ) by (host, group, site, application, segment, environment,instance)"
    }
   ]
  },
  {
   "title": "Cpu % Usage [5min]",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(host) (arubacx_system_cpu_usage_percent{group=~\"$group\",site=~\"$site\"})",
     "legendFormat": "{{ host }}"
    }
   ]
  },
  {
   "title": "Temperature Sensor",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "arubacx_thermals_temperature{group=~\"$group\",site=~\"$site\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "UPLINK Interface infos [$show_hostname]: [$interface]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "repeat": "interface",
   "collapsed": true,
   "panels": [
    {
     "title": "Admin Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "arubacx_if_admin_status{group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\", name=~\"$interface\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Link Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "arubacx_if_admin_status{group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\", name=~\"$interface\"}",
       "legendFormat": "{{ name }} {{ desc }}"
      }
     ]
    },
    {
     "title": "Link Error(CRC)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "arubacx_if_link_error{group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\", name=~\"$interface\"}",
       "legendFormat": "{{ name }} {{ desc }}"
      }
     ]
    },
    {
     "title": "Link Speed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "arubacx_if_link_speed{group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\", name=~\"$interface\"}",
       "legendFormat": "{{ name }} {{ desc }}"
      }
     ]
    },
    {
     "title": "Link Duplex",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "arubacx_if_link_duplex{group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\", name=~\"$interface\"}",
       "legendFormat": "{{ name }} {{ desc }}"
      }
     ]
    },
    {
     "title": "Throuput In/Out bit/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(arubacx_if_in_bytes{application=~\"$application\", site=~\"$site\", group=~\"$group\", host=~\"$show_hostname\", name=~\"$interface\"}[2m]) * 8",
       "legendFormat": "In {{ name }}/{{ desc }}"
      },
      {
       "expr": "rate(arubacx_if_out_bytes{application=~\"$application\", site=~\"$site\", group=~\"$group\", host=~\"$show_hostname\", name=~\"$interface\"}[2m]) * 8",
       "legendFormat": "Out {{ name }}/{{ desc }}"
      }
     ]
    },
    {
     "title": "Errors & Dropt In/Out packets/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(arubacx_if_in_dropped{application=~\"$application\", site=~\"$site\", group=~\"$group\", host=~\"$show_hostname\", name=~\"$interface\"}[2m]) * 8",
       "legendFormat": "In Dropped {{ name }}-{{ desc }}"
      },
      {
       "expr": "rate(arubacx_if_out_dropped{application=~\"$application\", site=~\"$site\", group=~\"$group\", host=~\"$show_hostname\", name=~\"$interface\"}[2m]) * 8",
       "legendFormat": "Out Dropped {{ name }}-{{ desc }}"
      },
      {
       "expr": "rate(arubacx_if_in_error{application=~\"$application\", site=~\"$site\", group=~\"$group\", host=~\"$show_hostname\", name=~\"$interface\"}[2m]) * 8",
       "legendFormat": "In Error {{ name }}-{{ desc }}"
      },
      {
       "expr": "rate(arubacx_if_out_error{application=~\"$application\", site=~\"$site\", group=~\"$group\", host=~\"$show_hostname\", name=~\"$interface\"}[2m]) * 8",
       "legendFormat": "Out Error {{ name }}-{{ desc }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Hardware [$show_hostname]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "OS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "arubacx_system_version{group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Software",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "arubacx_system_version{group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Product Name",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "arubacx_system_product_info{group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Serial Number",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "arubacx_system_product_info{group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Fan Status",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "arubacx_fans_status{site=~\"$site\", group=~\"$group\", host=~\"$show_hostname\"}",
       "legendFormat": "{{ name}}"
      }
     ]
    },
    {
     "title": "PowerSupply Status",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "arubacx_ps_status{site=~\"$site\", group=~\"$group\", host=~\"$show_hostname\"}",
       "legendFormat": "{{ name}}"
      }
     ]
    },
    {
     "title": "Storage Status",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "arubacx_storage_status{site=~\"$site\", group=~\"$group\", host=~\"$show_hostname\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Temperature Status",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
     "targets": [
      {
       "expr": "arubacx_thermals_status{group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Management Module Status",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
     "targets": [
      {
       "expr": "arubacx_system_management_module_status{group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "FAN speed (rpm)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 4, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "expr": "arubacx_fans_speed_rpm{site=~\"$site\", group=~\"$group\", host=~\"$show_hostname\"} != 0",
       "legendFormat": "FAN {{ name }}"
      }
     ]
    },
    {
     "title": "Power Consumption (Watt)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "arubacx_ps_consumption_watts{site=~\"$site\", group=~\"$group\", host=~\"$show_hostname\"}",
       "legendFormat": "PS {{ name }}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "arubacx_thermals_temperature{group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Temperature Value",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "expr": "arubacx_thermals_temperature{group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Infos [$show_hostname]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cpu Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "arubacx_system_cpu_usage_percent {group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\"}",
       "legendFormat": "% CPU"
      }
     ]
    },
    {
     "title": "Mem Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "arubacx_system_memory_usage_percent {group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\"}",
       "legendFormat": "{{ hrStorageDescr }} Usage %"
      }
     ]
    },
    {
     "title": "Open FDS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "arubacx_system_open_fds  {group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\"}",
       "legendFormat": "{{ hrStorageDescr }} Usage %"
      }
     ]
    },
    {
     "title": "Disks Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "arubacx_system_partition_percent_used{group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\"}",
       "legendFormat": "{{ partition }} Usage %"
      }
     ]
    },
    {
     "title": "Disks Write Op/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "rate(arubacx_system_partition_write_operation{group=~\"$group\",site=~\"$site\", host=~\"$show_hostname\"}[5m])",
       "legendFormat": "{{ partition }} write/s"
      }
     ]
    }
   ]
  }
 ]
}