{
 "title": "HP3PAR System",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(hp3par_up, host)" } }
  ]
 },
 "panels": [
  {
   "title": "system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hp3par_system_id{host=~\"$host\"}  "
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hp3par_system_id{host=~\"$host\"}  "
    }
   ]
  },
  {
   "title": "Patches",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hp3par_system_id{host=~\"$host\"}  "
    }
   ]
  },
  {
   "title": "Serial",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hp3par_system_id{host=~\"$host\"}  "
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hp3par_system_nodes_total{host=~\"$host\"}  "
    }
   ]
  },
  {
   "title": "Active Nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hp3par_system_nodes_active{host=~\"$host\"}  "
    }
   ]
  },
  {
   "title": "Total Capacity by Disk Type",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hp3par_capacity_total_bytes{host=~\"$host\"}  ",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Total free Capacity by disk type",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "hp3par_capacity_free_bytes{host=~\"$host\"}  ",
     "legendFormat": "{{ type}}"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "description": "average cluster cpu usage ( over all cpu and all cluster's nodes)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by(mode) (hp3par_cpu_usage_percent{ mode != \"idle\"})",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Memory IO cache hit percent",
   "type": "timeseries",
   "description": "Hits divided accesses displayed in percentage. (hitIO / accessIO percent) over 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hp3par_memory_hit_percent{host=~\"$host\"}",
     "legendFormat": "node: {{ node }} - {{ mode }}"
    }
   ]
  },
  {
   "title": "Memory Page details",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hp3par_memory_page_stats{host=~\"$host\"}",
     "legendFormat": "node: {{ node }} - pages {{ mode }}"
    }
   ]
  },
  {
   "title": "CPG",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Common Provisionning Groups",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(host, name) (hp3par_cpg_total_bytes{host=~\"$host\"}) != 0"
      },
      {
       "expr": "sum by(host, name) (hp3par_cpg_available_bytes{host=~\"$host\"}) != 0"
      },
      {
       "expr": "( sum by(host, name) (hp3par_cpg_total_bytes{host=~\"$host\"}) - sum by(host, name) (hp3par_cpg_available_bytes{host=~\"$host\"}) )/ (sum by(host, name) (hp3par_cpg_total_bytes{host=~\"$host\"}) +1 ) != 0"
      },
      {
       "expr": "sum by(host, name) (hp3par_cpg_snapshot_used_bytes{host=~\"$host\"}) != 0"
      }
     ]
    },
    {
     "title": "CPG Used %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "( sum by(host, name) (hp3par_cpg_total_bytes{host=~\"$host\"}) - sum by(host, name) (hp3par_cpg_available_bytes{host=~\"$host\"}) )/ (sum by(host, name) (hp3par_cpg_total_bytes{host=~\"$host\"}) +1 ) ",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "CPG Snapshots Used Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "( sum by(host, name) (hp3par_cpg_snapshot_used_bytes{host=~\"$host\"})) != 0",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Volumes Infos",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(host, name, provisionningtype) (hp3par_volume_total_bytes{host=~\"$host\"})"
    },
    {
     "expr": "sum by(host, name, provisionningtype) (hp3par_volume_used_bytes{host=~\"$host\"})"
    },
    {
     "expr": "sum by(host, name, provisionningtype) (hp3par_volume_used_bytes{host=~\"$host\"}) / sum by(host, name, provisionningtype) (hp3par_volume_total_bytes{host=~\"$host\"})"
    },
    {
     "expr": "sum by(host, name, provisionningtype) (hp3par_volume_compaction_ratio{host=~\"$host\"})"
    },
    {
     "expr": "sum by(host, name, provisionningtype) (hp3par_volume_deduplication_ratio{host=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Volumes IO operations by sec over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "hp3par_volume_read_io_per_second{host=~\"$host\"}",
     "legendFormat": "{{ name }}: read"
    },
    {
     "expr": "hp3par_volume_write_io_per_second{host=~\"$host\"}",
     "legendFormat": "{{ name }}: write"
    }
   ]
  },
  {
   "title": "Volumes IO Bytes by sec over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "hp3par_volume_read_bytes_per_second{host=~\"$host\"}",
     "legendFormat": "{{ name }}: read"
    },
    {
     "expr": "hp3par_volume_write_bytes_per_second{host=~\"$host\"}",
     "legendFormat": "{{ name }}: write"
    }
   ]
  },
  {
   "title": "Volumes IO latency over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "hp3par_volume_read_latency_second{host=~\"$host\"}",
     "legendFormat": "{{ name }}: read"
    },
    {
     "expr": "hp3par_volume_write_latency_second{host=~\"$host\"}",
     "legendFormat": "{{ name }}: write"
    }
   ]
  },
  {
   "title": "Volumes Busy % over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "hp3par_volume_busy_percent{host=~\"$host\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Physical disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Physical disks",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "avg by( cageID, cageSide,magazine,diskPos) (hp3par_physical_disk_total_bytes{host=~\"$host\"})",
       "legendFormat": "{{ id }}"
      },
      {
       "expr": "avg by( cageID, cageSide,magazine,diskPos) (hp3par_physical_disk_failed_bytes{host=~\"$host\"})",
       "legendFormat": "{{ id }}"
      },
      {
       "expr": "avg by( cageID, cageSide,magazine,diskPos) (hp3par_physical_disk_free_bytes{host=~\"$host\"} )",
       "legendFormat": "{{ id }}"
      },
      {
       "expr": "hp3par_physical_disk_free_bytes{host=~\"$host\"} / hp3par_physical_disk_total_bytes{host=~\"$host\"} * 100"
      },
      {
       "expr": "avg by( cageID, cageSide,magazine,diskPos) (hp3par_physical_disk_life_left_percent{host=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Disk Temperature in Celsius",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "hp3par_physical_disk_temperature{host=~\"$host\"}",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "Disk usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "hp3par_physical_disk_total_bytes{host=~\"$host\"} - hp3par_physical_disk_free_bytes{host=~\"$host\"}",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Physical ports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Port Status",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "sum by(source, target, label, porttype, protocol) (hp3par_port_status{host=~\"$host\"})"
      },
      {
       "expr": "sum by(source, target, label, porttype, protocol) (hp3par_port_failover_state{host=~\"$host\"})"
      }
     ]
    },
    {
     "title": "Port IO operations by sec over 5 min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hp3par_port_read_io_per_second{host=~\"$host\"}",
       "legendFormat": "{{ source }} {{ porttype}}: read"
      },
      {
       "expr": "hp3par_port_write_io_per_second{host=~\"$host\"}",
       "legendFormat": "{{ source }} {{ porttype}}: write"
      }
     ]
    },
    {
     "title": "Port IO Bytes by sec over 5 min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "hp3par_port_read_bytes_per_second{host=~\"$host\"}",
       "legendFormat": "{{ source }} {{ porttype}}: read"
      },
      {
       "expr": "hp3par_port_write_bytes_per_second{host=~\"$host\"}",
       "legendFormat": "{{ source }} {{ porttype}}: write"
      }
     ]
    },
    {
     "title": "Port IO latency over 5 min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "hp3par_port_read_latency_second{host=~\"$host\"}",
       "legendFormat": "{{ source }} {{ porttype}}: read"
      },
      {
       "expr": "hp3par_port_write_latency_second{host=~\"$host\"}",
       "legendFormat": "{{ source }} {{ porttype}}: write"
      }
     ]
    },
    {
     "title": "Port Busy % over 5 min",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "hp3par_port_busy_percent{host=~\"$host\"}",
       "legendFormat": "{{ source }} {{ porttype }}"
      }
     ]
    }
   ]
  }
 ]
}