{
 "title": "CITRIX ADC Netscaler Stats",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "segment",
    "label": "Segment",
    "query": {
     "query": "label_values(citrixadc_up, segment)"
    }
   },
   {
    "name": "host",
    "label": "Hostname",
    "query": {
     "query": "label_values(citrixadc_up{segment=~\"$segment\"}, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Edition",
     "type": "stat",
     "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "citrixadc_bandwidth_licensed{host=~\"$host\"}"
      }
     ]
    },
    {
     "title": "version",
     "type": "stat",
     "gridPos": { "h": 3, "w": 15, "x": 9, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "citrixadc_bandwidth_licensed{host=~\"$host\"}"
      }
     ]
    },
    {
     "title": "HA Available",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "citrixadc_ha_available{host=~\"$host\"}"
      }
     ]
    },
    {
     "title": "Licensed Bandwidth",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "citrixadc_bandwidth_licensed{host=~\"$host\"}"
      }
     ]
    }
   ]
  },
  { "title": "High Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "citrixadc_ha_state{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "citrixadc_ha_node_state{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Last transition",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "citrixadc_ha_node_start_timestamp{host=~\"$host\"}*1000"
    }
   ]
  },
  {
   "title": "Propagation timeout Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "citrixadc_ha_node_propagation_timeout{host=~\"$host\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Sync Failure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "citrixadc_ha_node_sync_failure{host=~\"$host\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "State",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "citrixadc_up{host=~\"$host\"}"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "citrixadc_system_start_timestamp{host=~\"$host\"} * 1000"
      }
     ]
    },
    {
     "title": "CPU ",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "citrixadc_system_cpu_count{host=~\"$host\"}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "citrixadc_system_memory_total_available_bytes{host=~\"$host\"}"
      }
     ]
    },
    {
     "title": "Licensed Throughput percent (stacked)",
     "type": "graph",
     "gridPos": { "h": 11, "w": 16, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "( citrixadc_ns_rx_mbits_rate {host=~\"$host\"} / sum(citrixadc_bandwidth_licensed{host=~\"$host\"}) without(edition,version) )",
       "legendFormat": "received"
      },
      {
       "expr": "( citrixadc_ns_tx_mbits_rate {host=~\"$host\"} / sum(citrixadc_bandwidth_licensed{host=~\"$host\"}) without(edition,version) )",
       "legendFormat": "transmitted"
      },
      {
       "expr": "( (citrixadc_ns_rx_mbits_rate {host=~\"$host\"} + citrixadc_ns_tx_mbits_rate {host=~\"$host\"}) / sum(citrixadc_bandwidth_licensed{host=~\"$host\"}) without(edition,version) )",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Licensed Throughput rate (stacked) ",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "yaxes": [
      { "format": "Mbits" }
     ],
     "targets": [
      {
       "expr": "citrixadc_ns_rx_mbits_rate {host=~\"$host\"}",
       "legendFormat": "received"
      },
      {
       "expr": "citrixadc_ns_tx_mbits_rate {host=~\"$host\"}",
       "legendFormat": "transmitted"
      },
      {
       "expr": "citrixadc_bandwidth_licensed{host=~\"$host\"}",
       "legendFormat": "Licensed Bandwidth"
      }
     ]
    },
    {
     "title": "CPU Utilization Percentage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "citrixadc_system_packet_cpu_usage_percent{host=~\"$host\"}",
       "legendFormat": "pkt processing usage"
      },
      {
       "expr": "citrixadc_system_management_cpu_usage_percent{host=~\"$host\"}",
       "legendFormat": "management"
      }
     ]
    },
    {
     "title": "Memory Utilization Percentage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "citrixadc_system_memory_usage_percent{host=~\"$host\"}",
       "legendFormat": "mem % used"
      },
      {
       "expr": "citrixadc_system_memory_shared_usage_percent{host=~\"$host\"}",
       "legendFormat": "shared % used"
      },
      {
       "expr": "citrixadc_system_memory_allocated_percent{host=~\"$host\"}",
       "legendFormat": "allocated % used"
      }
     ]
    },
    {
     "title": "Disk Usage %",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "citrixadc_system_disk_used_percent{host=~\"$host\"}",
       "legendFormat": "{{ mount }}"
      }
     ]
    },
    {
     "title": "Disk Free bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "citrixadc_system_disk_free_bytes{host=~\"$host\"}",
       "legendFormat": "{{ mount }} free"
      },
      {
       "expr": "citrixadc_system_disk_total_bytes{host=~\"$host\"}",
       "legendFormat": "{{ mount }} total"
      }
     ]
    }
   ]
  },
  {
   "title": "Interfaces Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average In/out Bits by second by interface",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_interface_tot_rx_bytes{host=~\"$host\"}[2m]) * 8",
       "legendFormat": "In {{ citrixadc_interface_id }}"
      },
      {
       "expr": "rate(citrixadc_interface_tot_tx_bytes{host=~\"$host\"}[2m]) * 8",
       "legendFormat": "Out {{ citrixadc_interface_id }}"
      }
     ]
    },
    {
     "title": "Instant In/out Bits by second by interface",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "citrixadc_interface_rx_bytes_rate{host=~\"$host\"} * 8",
       "legendFormat": "In {{ citrixadc_interface_id }}"
      },
      {
       "expr": "citrixadc_interface_tx_bytes_rate{host=~\"$host\"} * 8",
       "legendFormat": "Out {{ citrixadc_interface_id }}"
      }
     ]
    },
    {
     "title": "Multicast Packet by second by interface",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_interface_tot_multicast_packets{host=~\"$host\"}[2m])",
       "legendFormat": "Multicast pkt  {{ citrixadc_interface_id }}"
      }
     ]
    },
    {
     "title": "In/out Dropped Pkt by second by Interface",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_interface_err_dropped_rx_packets{host=~\"$host\"}[2m])",
       "legendFormat": "In {{ citrixadc_interface_id }}"
      },
      {
       "expr": "rate(citrixadc_interface_err_dropped_tx_packets{host=~\"$host\"}[2m])",
       "legendFormat": "Out {{ citrixadc_interface_id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "IP stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "In/out Bits by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_ip_tot_rx_bytes{host=~\"$host\"}[2m]) * 8",
       "legendFormat": "In"
      },
      {
       "expr": "rate(citrixadc_ip_tx_bytes{host=~\"$host\"}[2m]) *8 ",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "In/out Packets by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_ip_tot_rx_bytes{host=~\"$host\"}[2m])",
       "legendFormat": "In"
      },
      {
       "expr": "rate(citrixadc_ip_tx_bytes{host=~\"$host\"}[2m])",
       "legendFormat": "Out"
      }
     ]
    },
    {
     "title": "Packet routed by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_ip_tot_routed_packets{host=~\"$host\"}[2m])",
       "legendFormat": "routed"
      }
     ]
    },
    {
     "title": "packet stats",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_ip_tot_fragments{host=~\"$host\"}[2m])",
       "legendFormat": "fragmented"
      },
      {
       "expr": "rate(citrixadc_ip_tot_successful_assembly{host=~\"$host\"}[2m])",
       "legendFormat": "assembly"
      },
      {
       "expr": "rate(citrixadc_ip_tot_address_lookup{host=~\"$host\"}[2m])",
       "legendFormat": "lookup"
      },
      {
       "expr": "rate(citrixadc_ip_tot_address_lookup_fail{host=~\"$host\"}[2m])",
       "legendFormat": "Failed lookup"
      },
      {
       "expr": "rate(citrixadc_ip_tot_udp_fragments_forwarded{host=~\"$host\"}[2m])",
       "legendFormat": "udp fragments fwd"
      },
      {
       "expr": "rate(citrixadc_ip_tot_tcp_fragments_forwarded{host=~\"$host\"}[2m])",
       "legendFormat": "tcp fragments fwd"
      },
      {
       "expr": "rate(citrixadc_ip_tot_bad_checksums{host=~\"$host\"}[2m])",
       "legendFormat": "bad checksum"
      }
     ]
    }
   ]
  },
  {
   "title": "UDP stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "In/out bits by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "yaxes": [
      { "format": "decbits" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_udp_tot_rx_bytes{host=~\"$host\"}[2m])",
       "legendFormat": "In {{ host }}"
      },
      {
       "expr": "rate(citrixadc_udp_tot_tx_bytes{host=~\"$host\"}[2m])",
       "legendFormat": "Out {{ host }}"
      }
     ]
    },
    {
     "title": "In / Out packets by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_udp_tot_rx_packets{host=~\"$host\"}[2m]) * 8",
       "legendFormat": "In {{ host }}"
      },
      {
       "expr": "rate(citrixadc_udp_tot_tx_packets{host=~\"$host\"}[2m]) *8 ",
       "legendFormat": "Out {{ host }}"
      }
     ]
    },
    {
     "title": "Unknown - bad checksum packets by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_udp_tot_unknown_service_packets{host=~\"$host\"}[2m]) * 8",
       "legendFormat": "Unknown {{ host }}"
      },
      {
       "expr": "rate(citrixadc_udp_tot_bad_checksum_packets{host=~\"$host\"}[2m]) *8 ",
       "legendFormat": "bad checksum {{ host }}"
      }
     ]
    }
   ]
  },
  {
   "title": "TCP Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "In/out bits by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_tcp_tot_rx_bytes{host=~\"$host\"}[2m]) * 8 ",
       "legendFormat": "In {{ host }}"
      },
      {
       "expr": "rate(citrixadc_tcp_tot_tx_bytes{host=~\"$host\"}[2m]) * 8",
       "legendFormat": "Out {{ host }}"
      }
     ]
    },
    {
     "title": "In/out packets by second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_tcp_tot_rx_packets{host=~\"$host\"}[2m])",
       "legendFormat": "In {{ host }}"
      },
      {
       "expr": "rate(citrixadc_tcp_tot_tx_packets{host=~\"$host\"}[2m])",
       "legendFormat": "Out {{ host }}"
      }
     ]
    },
    {
     "title": "TCP metrics by second",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_tcp_tot_client_connections_opened{host=~\"$host\"}[2m])",
       "legendFormat": "client opened cnx {{ host }}"
      },
      {
       "expr": "rate(citrixadc_tcp_tot_server_connections_opened{host=~\"$host\"}[2m])",
       "legendFormat": "server opened cnx {{ host }}"
      },
      {
       "expr": "rate(citrixadc_tcp_tot_syn{host=~\"$host\"}[2m])",
       "legendFormat": "SYN received {{ host }}"
      },
      {
       "expr": "rate(citrixadc_tcp_tot_client_fin{host=~\"$host\"}[2m])",
       "legendFormat": "client FIN received {{ host }}"
      },
      {
       "expr": "rate(citrixadc_tcp_tot_server_fin{host=~\"$host\"}[2m])",
       "legendFormat": "server FIN received {{ host }}"
      },
      {
       "expr": "rate(citrixadc_tcp_tot_syn_probe{host=~\"$host\"}[2m])",
       "legendFormat": "PROBE {{ host }}"
      }
     ]
    },
    {
     "title": "TCP \"errors\" packets by second",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_tcp_err_full_retransmit{host=~\"$host\"}[2m])",
       "legendFormat": "full retransmitted {{ host }}"
      },
      {
       "expr": "rate(citrixadc_tcp_err_badchecksum{host=~\"$host\"}[2m])",
       "legendFormat": "bad chksum {{ host }}"
      },
      {
       "expr": "rate(citrixadc_tcp_err_reset_threshold{host=~\"$host\"}[2m])",
       "legendFormat": "RESET {{ host }}"
      },
      {
       "expr": "rate(citrixadc_tcp_err_bad_connection_state{host=~\"$host\"}[2m])",
       "legendFormat": "BAD state {{ host }}"
      },
      {
       "expr": "rate(citrixadc_tcp_err_out_of_window{host=~\"$host\"}[2m])",
       "legendFormat": "out of window {{ host }}"
      },
      {
       "expr": "rate(citrixadc_tcp_err_syn_dropped_congestion{host=~\"$host\"}[2m])",
       "legendFormat": "SYN dropped congestion {{ host }}"
      },
      {
       "expr": "rate(citrixadc_tcp_err_any_port_fail{host=~\"$host\"}[2m])",
       "legendFormat": "any port fail {{ host }}"
      }
     ]
    }
   ]
  },
  { "title": "HTTP Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Request,  Response by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_http_tot_requests{host=~\"$host\"}[2m])",
     "legendFormat": "Requests {{ host }}"
    },
    {
     "expr": "rate(citrixadc_http_tot_responses{host=~\"$host\"}[2m])",
     "legendFormat": "Responses  {{ host }}"
    }
   ]
  },
  {
   "title": "Request,  Response instant value by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "citrixadc_http_requests_rate{host=~\"$host\"}",
     "legendFormat": "Requests {{ host }}"
    },
    {
     "expr": "citrixadc_http_responses_rate{host=~\"$host\"}",
     "legendFormat": "Responses  {{ host }}"
    }
   ]
  },
  {
   "title": "HTTP request/response by version by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_http_tot_10_requests{host=~\"$host\"}[2m])",
     "legendFormat": "HTTP 1.0 req {{ host }}"
    },
    {
     "expr": "rate(citrixadc_http_tot_11_requests{host=~\"$host\"}[2m])",
     "legendFormat": "HTTP 1.1 req {{ host }}"
    },
    {
     "expr": "rate(citrixadc_http_tot_10_responses{host=~\"$host\"}[2m])",
     "legendFormat": "HTTP 1.0 response  {{ host }}"
    },
    {
     "expr": "rate(citrixadc_http_tot_10_responses{host=~\"$host\"}[2m])",
     "legendFormat": "HTTP 1.1 response {{ host }}"
    }
   ]
  },
  {
   "title": "HTTP methods by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_http_tot_gets{host=~\"$host\"}[2m])",
     "legendFormat": "GET {{ host }}"
    },
    {
     "expr": "rate(citrixadc_http_tot_posts{host=~\"$host\"}[2m])",
     "legendFormat": "POST {{ host }}"
    },
    {
     "expr": "rate(citrixadc_http_tot_others{host=~\"$host\"}[2m])",
     "legendFormat": "others {{ host }}"
    }
   ]
  },
  {
   "title": "HTTP chunked by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_http_tot_chunked_requests{host=~\"$host\"}[2m])",
     "legendFormat": "req {{ host }}"
    },
    {
     "expr": "rate(citrixadc_http_tot_chunked_responses{host=~\"$host\"}[2m])",
     "legendFormat": "response {{ host }}"
    }
   ]
  },
  {
   "title": "HTTP \"errors\" by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_http_err_tot_incomplete_header_packets{host=~\"$host\"}[2m])",
     "legendFormat": "incomplete header {{ host }}"
    },
    {
     "expr": "rate(citrixadc_http_err_tot_server_responses{host=~\"$host\"}[2m])",
     "legendFormat": "error response {{ host }}"
    },
    {
     "expr": "rate(citrixadc_http_err_tot_large_body_packets{host=~\"$host\"}[2m])",
     "legendFormat": "too large body {{ host }}"
    },
    {
     "expr": "rate(citrixadc_http_err_tot_large_chunk_requests{host=~\"$host\"}[2m])",
     "legendFormat": "too large chunked size {{ host }}"
    },
    {
     "expr": "rate(citrixadc_http_err_tot_large_content_requests{host=~\"$host\"}[2m])",
     "legendFormat": "too large content size {{ host }}"
    }
   ]
  },
  {
   "title": "Load Balacing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "LBC Overview",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "citrixadc_lb_inactive_services_count{host=~\"$host\"}"
      },
      {
       "expr": "count(citrixadc_servicegroup_status{host=~\"$host\"})  without(citrixadc_service_ip, citrixadc_service_port, citrixadc_servicegroup_name,citrixadc_servicegroup_membername)"
      },
      {
       "expr": "citrixadc_lb_hits_rate{host=~\"$host\"}"
      },
      {
       "expr": "citrixadc_lb_actual_server_current_connections{host=~\"$host\"}"
      },
      {
       "expr": "citrixadc_lb_current_client_connection_count{host=~\"$host\"}"
      },
      {
       "expr": "citrixadc_lb_active_sessions_count {host=~\"$host\"}"
      },
      {
       "expr": "citrixadc_lb_average_ttlb{host=~\"$host\"}"
      },
      {
       "expr": "rate(citrixadc_lb_hits_total{host=~\"$host\"}[2m])"
      },
      {
       "expr": "avg_over_time(citrixadc_lb_busy_error_total{host=~\"$host\"}[$__range])"
      },
      {
       "expr": "rate(citrixadc_lb_requests_total{host=~\"$host\"}[2m])"
      },
      {
       "expr": "rate(citrixadc_lb_responses_total{host=~\"$host\"}[2m])"
      }
     ]
    },
    {
     "title": "Total Hits/s by LB Service",
     "type": "graph",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_lb_hits_total{host=~\"$host\"}[2m])",
       "legendFormat": "{{ lb_name }} {{ lb_type }}"
      }
     ]
    },
    {
     "title": "percent of members UP for service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum by(lb_name) (citrixadc_lb_members_up_total{host=~\"$host\"})",
       "legendFormat": "client connection {{ lb_name }}"
      }
     ]
    }
   ]
  },
  { "title": "SSL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "SSL V2 session by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_ssl_tot_tlsv11_sessions{host=~\"$host\"}[2m])",
     "legendFormat": "TLSv1 session"
    },
    {
     "expr": "rate(citrixadc_ssl_tot_v2_sessions{host=~\"$host\"}[2m])",
     "legendFormat": "SSLv2 session"
    }
   ]
  },
  {
   "title": "Total SSL session by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_ssl_tot_sessions{host=~\"$host\"}[2m])",
     "legendFormat": "num"
    }
   ]
  },
  {
   "title": "Total SSL encode by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_ssl_tot_encode{host=~\"$host\"}[2m])",
     "legendFormat": "num"
    }
   ]
  },
  {
   "title": "Total SSL crypto usage by second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_ssl_crypto_utilization_stat{host=~\"$host\"}[2m])",
     "legendFormat": "num"
    }
   ]
  },
  {
   "title": "SSL Services Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "citrixadc_sslvserver_status{host=~\"$host\"}"
    },
    {
     "expr": "citrixadc_sslvserver_active_services{host=~\"$host\"}"
    },
    {
     "expr": "citrixadc_sslvserver_health{host=~\"$host\"}"
    },
    {
     "expr": "rate(citrixadc_sslvserver_total_session_new{host=~\"$host\"}[5m])"
    },
    {
     "expr": "rate(citrixadc_sslvserver_total_decrypt_bytes{host=~\"$host\"}[5m])"
    },
    {
     "expr": "rate(citrixadc_sslvserver_total_encrypt_bytes{host=~\"$host\"}[5m])"
    },
    {
     "expr": "rate(citrixadc_sslvserver_total_decrypt_hardware_bytes{host=~\"$host\"}[5m])"
    },
    {
     "expr": "rate(citrixadc_sslvserver_total_encrypt_hardware_bytes{host=~\"$host\"}[5m])"
    }
   ]
  },
  {
   "title": "Certificate expiration",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "citrixadc_ssl_cert_days_to_expire{host=~\"$host\"}"
    },
    {
     "expr": "(time() + (citrixadc_ssl_cert_days_to_expire{host=~\"$host\"} * 86400)) * 1000"
    }
   ]
  },
  {
   "title": "AAA Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Auth",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 158 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_aaa_auth_success{host=~\"$host\"}[2m])",
       "legendFormat": "success auth"
      },
      {
       "expr": "rate(citrixadc_aaa_auth_fail{host=~\"$host\"}[2m])",
       "legendFormat": "failed auth"
      }
     ]
    },
    {
     "title": "Session",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 158 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(citrixadc_aaa_tot_sessions{host=~\"$host\"}[2m])",
       "legendFormat": "Total session"
      },
      {
       "expr": "rate(citrixadc_aaa_tot_sessiontimeout{host=~\"$host\"}[2m])",
       "legendFormat": "Timeout session"
      },
      {
       "expr": "rate(citrixadc_aaa_tot_tm_sessions{host=~\"$host\"}[2m])",
       "legendFormat": "TM? session"
      }
     ]
    },
    {
     "title": "ICA",
     "type": "graph",
     "description": "Count of current Basic ICA only connections.\nCount of current SmartAccess ICA connections.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 167 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "citrixadc_aaa_cur_ica_conn{host=~\"$host\"}",
       "legendFormat": "SmartAccess ICA"
      },
      {
       "expr": "citrixadc_aaa_cur_ica_only_conn{host=~\"$host\"}",
       "legendFormat": "Basic ICA only conn"
      }
     ]
    }
   ]
  }
 ]
}