{
 "title": "CITRIX ADC Netscaler LB Services Stats",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "segment",
    "label": "Segment",
    "query": {
     "query": "label_values(citrixadc_up, segment)"
    }
   },
   {
    "name": "host",
    "label": "Hostname",
    "query": {
     "query": "label_values(citrixadc_up{segment=~\"$segment\"}, host)"
    }
   },
   {
    "name": "service",
    "label": "LBC service",
    "query": {
     "query": "label_values(citrixadc_lb_status{segment=~\"$segment\", host=~\"$host\"}, lb_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "LB service Stats $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "requests & responses by second for $service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum( rate(citrixadc_lb_requests_total{host=~\"$host\", lb_name=~\"$service\"}[2m]) )",
     "legendFormat": "requests {{ lb_name}}"
    },
    {
     "expr": "sum( rate(citrixadc_lb_responses_total{host=~\"$host\", lb_name=~\"$service\"}[2m]) )",
     "legendFormat": "Responses {{ lb_name}}"
    }
   ]
  },
  {
   "title": "Stats by second for $service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "yaxes": [
    { "format": "cps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(citrixadc_lb_hits_total{host=~\"$host\", lb_name=~\"$service\"}[2m]))",
     "legendFormat": "Hits"
    },
    {
     "expr": "sum(rate(citrixadc_lb_surge_count_total{host=~\"$host\", lb_name=~\"$service\"}[2m]) )",
     "legendFormat": "Surge"
    },
    {
     "expr": "sum( rate(citrixadc_lb_tolerable_transactions_count_total{host=~\"$host\", lb_name=~\"$service\"}[2m]))",
     "legendFormat": "Tolerable Transactions"
    },
    {
     "expr": "sum( rate(citrixadc_lb_ttlb_calculated_transactions_total{host=~\"$host\", lb_name=~\"$service\"}[2m]) )",
     "legendFormat": "Calculated Transactions"
    },
    {
     "expr": "sum( rate(citrixadc_lb_deffered_requests_total{host=~\"$host\", lb_name=~\"$service\"}[2m]) )",
     "legendFormat": "deffered req"
    },
    {
     "expr": "sum( rate(citrixadc_lb_spillover_count_total{host=~\"$host\", lb_name=~\"$service\"}[2m]) )",
     "legendFormat": "Spillover"
    },
    {
     "expr": "sum( rate(citrixadc_lb_invalid_response_request_total{host=~\"$host\", lb_name=~\"$service\"}[2m]) )",
     "legendFormat": "invalid req"
    },
    {
     "expr": "sum( rate(citrixadc_lb_invalid_response_request_dropped_total{host=~\"$host\", lb_name=~\"$service\"}[2m]))",
     "legendFormat": "dropped req"
    },
    {
     "expr": "sum( rate(citrixadc_lb_busy_error_total{host=~\"$host\", lb_name=~\"$service\"}[2m]) )",
     "legendFormat": "busy error"
    }
   ]
  },
  {
   "title": "Bytes In/Out by sec for $service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(citrixadc_lb_request_bytes_received_total{host=~\"$host\", lb_name=~\"$service\"}[2m]))",
     "legendFormat": "In"
    },
    {
     "expr": "sum( rate(citrixadc_lb_response_bytes_received_total{host=~\"$host\", lb_name=~\"$service\"}[2m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Packet In/Out by sec for $service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum( rate(citrixadc_lb_packets_received_total{host=~\"$host\", lb_name=~\"$service\"}[2m]) )",
     "legendFormat": "In"
    },
    {
     "expr": "sum(rate(citrixadc_lb_packets_sent_total{host=~\"$host\", lb_name=~\"$service\"}[2m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "current client connection for $service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(citrixadc_lb_current_client_connection_count{host=~\"$host\", lb_name=~\"$service\"})",
     "legendFormat": "client connection {{ lb_name }}"
    }
   ]
  },
  {
   "title": "percent of members UP for $service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(citrixadc_lb_members_up_total{host=~\"$host\", lb_name=~\"$service\"})",
     "legendFormat": "client connection {{ lb_name }}"
    }
   ]
  },
  {
   "title": " $service Service Member Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Service Member Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "citrixadc_servicegroup_status{host=~\"$host\", lb_name\r=~\"$service\"}"
    },
    {
     "expr": "citrixadc_servicegroup_current_client_connections{host=~\"$host\", lb_name=~\"$service\"}"
    },
    {
     "expr": "citrixadc_servicegroup_current_server_connections{host=~\"$host\", lb_name=~\"$service\"}"
    }
   ]
  },
  {
   "title": "client connection for $service by members",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citrixadc_servicegroup_current_client_connections{host=~\"$host\", lb_name=~\"$service\"}",
     "legendFormat": "{{ servicegroup_membername}}"
    }
   ]
  },
  {
   "title": "current server connections for $service by members",
   "type": "graph",
   "description": "Number of current connections to the actual servers behind the virtual server",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citrixadc_servicegroup_current_server_connections{host=~\"$host\", lb_name=~\"$service\"}",
     "legendFormat": "{{ servicegroup_membername}}"
    }
   ]
  },
  {
   "title": "Member status  for $service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citrixadc_servicegroup_status{host=~\"$host\", lb_name=~\"$service\"}",
     "legendFormat": "{{ servicegroup_membername}} status"
    }
   ]
  },
  {
   "title": "req / rep rate for $service by members",
   "type": "graph",
   "description": "Number of responses received on this service or virtual server. (This applies to HTTP/SSL services and servers.)\nTotal number of requests received on this service or virtual server. (This applies to HTTP/SSL services and servers.)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "- Request / + Reponses " }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_servicegroup_tot_requests{host=~\"$host\", lb_name=~\"$service\"}[1m])",
     "legendFormat": "req/s {{ servicegroup_membername}}"
    },
    {
     "expr": "rate(citrixadc_servicegroup_tot_responses{host=~\"$host\", lb_name=~\"$service\"}[1m])",
     "legendFormat": "rep/s {{ servicegroup_membername}}"
    }
   ]
  },
  {
   "title": "req / rep bytes rate for $service by members",
   "type": "graph",
   "description": "rate of total number of response bytes received by this service or virtual server\nrate of total number of request bytes received on this service or virtual server",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps", "label": "- Request / + Reponses " }
   ],
   "targets": [
    {
     "expr": "rate(citrixadc_servicegroup_tot_request_bytes{host=~\"$host\", lb_name=~\"$service\"}[1m])",
     "legendFormat": "req/s {{ servicegroup_membername}}"
    },
    {
     "expr": "rate(citrixadc_servicegroup_tot_response_bytes{host=~\"$host\", lb_name=~\"$service\"}[1m])",
     "legendFormat": "rep/s {{ servicegroup_membername}}"
    }
   ]
  },
  {
   "title": "avg TTFB  for $service",
   "type": "graph",
   "description": "Average TTFB between the NetScaler appliance and the server.TTFB is the time interval between sending the request packet to a service and receiving the first response from the service",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citrixadc_servicegroup_avg_server_ttfb{host=~\"$host\", lb_name=~\"$service\"}",
     "legendFormat": "{{ servicegroup_membername}}"
    }
   ]
  }
 ]
}