{
 "title": "CITRIX ADC Netscaler SSL Services Stats",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "segment",
    "label": "Segment",
    "query": {
     "query": "label_values(citrixadc_up, segment)"
    }
   },
   {
    "name": "host",
    "label": "Hostname",
    "query": {
     "query": "label_values(citrixadc_up{segment=~\"$segment\"}, host)"
    }
   },
   {
    "name": "service",
    "label": "SSL service",
    "query": {
     "query": "label_values(citrixadc_sslvserver_status{segment=~\"$segment\", host=~\"$host\"}, sslvserver_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SSL Service Stats $service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "service",
   "targets": [
    {}
   ]
  },
  {
   "title": "SSL Encrypt/Decrypt bytes/s $service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(citrixadc_sslvserver_total_decrypt_bytes{host=~\"$host\", sslvserver_name=~\"$service\"}[2m])",
     "legendFormat": "decrypted {{ sslvserver_name }}"
    },
    {
     "expr": "rate(citrixadc_sslvserver_total_encrypt_bytes{host=~\"$host\", sslvserver_name=~\"$service\"}[2m])",
     "legendFormat": "encrypted {{ sslvserver_name }}"
    }
   ]
  },
  {
   "title": "SSL Hardaware Encrypt/Decrypt bytes/s $service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(citrixadc_sslvserver_total_auth_success{host=~\"$host\", sslvserver_name=~\"$service\"}[2m])",
     "legendFormat": "auth success {{ sslvserver_name }}"
    },
    {
     "expr": "rate(citrixadc_sslvserver_total_auth_failure{host=~\"$host\", sslvserver_name=~\"$service\"}[2m])",
     "legendFormat": "auth failure {{ sslvserver_name }}"
    }
   ]
  },
  {
   "title": "SSL SubService Health $service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "citrixadc_sslvserver_health{host=~\"$host\", sslvserver_name=~\"$service\"}",
     "legendFormat": "subservice health % {{ sslvserver_name }}"
    },
    {
     "expr": "citrixadc_sslvserver_active_services{host=~\"$host\", sslvserver_name=~\"$service\"}",
     "legendFormat": "active service {{ sslvserver_name }}"
    }
   ]
  },
  {
   "title": "SSL new session and hits /s for $service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(citrixadc_sslvserver_total_session_new{host=~\"$host\", sslvserver_name=~\"$service\"}[2m])",
     "legendFormat": "new  session {{ sslvserver_name }}"
    },
    {
     "expr": "rate(citrixadc_sslvserver_total_session_hits{host=~\"$host\", sslvserver_name=~\"$ssl_service\"}[2m])",
     "legendFormat": "hits {{ sslvserver_name }}"
    }
   ]
  }
 ]
}