{
 "title": "Apache Server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(apache_up,application)"
    }
   },
   {
    "name": "env",
    "label": "environment",
    "query": {
     "query": "label_values(apache_up{application=~\"$application\"},environment)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(apache_up{application=~\"$application\", environment=~\"$env\"},instance)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(apache_up{application=~\"$application\", environment=~\"$env\", instance=~\"${host}.*\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ressource Summary ${application}",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(application, env, host)(apache_up{application=~\"$application\", environment=~\"$env\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(application, env, host)(apache_uptime_seconds_total{application=~\"$application\", environment=~\"$env\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(application, env, host)(apache_cpuload{application=~\"$application\", environment=~\"$env\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(application, env, host)(increase(apache_accesses_total{application=~\"$application\", environment=~\"$env\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(application, env, host)(apache_connections{application=~\"$application\", environment=~\"$env\", state=\"total\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(application, env, host) (apache_workers{application=~\"$application\", environment=~\"$env\", state=\"busy\"})\r\n/\r\nsum by(application, env, host) (apache_workers{application=~\"$application\", environment=~\"$env\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_info{application=~\"$application\", environment=~\"$env\",instance=~\"$host:$port\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg by(shortname) (label_replace(\r\n    apache_uptime_seconds_total{application=~\"$application\", environment=~\"$env\",instance=~\"$host:$port\"}\r\n    , \"shortname\", \"$short\", \"instance\", \"^(?P<short>[^.]+).*\")\r\n)",
     "legendFormat": "{{ shortname }}"
    }
   ]
  },
  {
   "title": "Apache Up / Down",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(shortname) (label_replace(\r\n    avg by(instance) (apache_up{application=~\"$application\", environment=~\"$env\",instance=~\"$host:$port\"})\r\n    , \"shortname\", \"$short\", \"instance\", \"^(?P<short>[^.]+).*\")\r\n)",
     "legendFormat": "{{ shortname }} Apache Up"
    }
   ]
  },
  {
   "title": "Current total apache accesses by sec over 5 min",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(shortname) (label_replace(\r\n    rate(apache_accesses_total{application=~\"$application\", environment=~\"$env\", instance=~\"$host:$port\"}[5m])\r\n    , \"shortname\", \"$short\", \"instance\", \"^(?P<short>[^.]+).*\")\r\n)",
     "legendFormat": "{{ shortname }} Accesses"
    }
   ]
  },
  {
   "title": "Total apache accesses by minutes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "avg by(shortname) (label_replace(\r\n    increase(apache_accesses_total{application=~\"$application\", environment=~\"$env\",instance=~\"$host:$port\"}[$__rate_interval])\r\n    , \"shortname\", \"$short\", \"instance\", \"^(?P<short>[^.]+).*\")\r\n)",
     "legendFormat": "{{shortname}} access"
    }
   ]
  },
  {
   "title": "Current total kbytes sent by sec over 5min",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "avg by(shortname) (label_replace(\r\n    rate(apache_sent_kilobytes_total{application=~\"$application\", environment=~\"$env\",instance=~\"$host:$port\"}[5m])\r\n    , \"shortname\", \"$short\", \"instance\", \"^(?P<short>[^.]+).*\")\r\n)",
     "legendFormat": "{{ shortname }} Kilobytes Sent"
    }
   ]
  },
  {
   "title": "average Requests Duration over 2 min",
   "type": "timeseries",
   "description": "sum of  requests duration in ms divide by sum of accesses on the same interval",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(shortname) (label_replace(\r\n    (\r\n        rate(apache_duration_ms_total{application=~\"$application\", environment=~\"$env\",instance=~\"$host:$port\"}[2m])\r\n        /\r\n        rate(apache_accesses_total{application=~\"$application\", environment=~\"$env\", instance=~\"$host:$port\"}[2m])\r\n    )\r\n    , \"shortname\", \"$short\", \"instance\", \"^(?P<short>[^.]+).*\")\r\n)",
     "legendFormat": "{{ shortname }} avg req duration"
    }
   ]
  },
  {
   "title": "Apache Connections count by type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(shortname) (label_replace(\n    apache_connections{application=~\"$application\", environment=~\"$env\",instance=~\"$host:$port\"}\n    , \"shortname\", \"$short\", \"instance\", \"^(?P<short>[^.]+).*\")\n)",
     "legendFormat": "{{ shortname }} {{ state }}"
    }
   ]
  },
  {
   "title": "Apache scoreboard statuses (sum all hosts)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (state) (apache_scoreboard{application=~\"$application\", environment=~\"$env\",instance=~\"$host:$port\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Apache worker statuses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(shortname) (label_replace(\n    apache_workers{application=~\"$application\", environment=~\"$env\",instance=~\"$host:$port\"}\n    , \"shortname\", \"$short\", \"instance\", \"^(?P<short>[^.]+).*\")\n)",
     "legendFormat": "{{ shortname }} {{ state }}"
    },
    {
     "expr": "avg by(shortname) (label_replace(\n    (\n        avg by(application, env, instance) (apache_workers{application=~\"$application\", environment=~\"$env\", state=\"busy\"})\n        /\n        sum by(application, env, instance) (apache_workers{application=~\"$application\", environment=~\"$env\"})\n    )\n    , \"shortname\", \"$short\", \"instance\", \"^(?P<short>[^.]+).*\")\n)",
     "legendFormat": "{{ shortname }} busy %"
    }
   ]
  },
  {
   "title": "Apache CPU load",
   "type": "timeseries",
   "description": "The current percentage CPU used by each worker and in total by all workers combined",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(shortname) (label_replace(\r\n    apache_cpuload{application=~\"$application\", environment=~\"$env\",instance=~\"$host:$port\"}\r\n    , \"shortname\", \"$short\", \"instance\", \"^(?P<short>[^.]+).*\")\r\n)",
     "legendFormat": "{{ shortname }} Load"
    }
   ]
  },
  {
   "title": "Apache Server load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(shortname) (label_replace(\r\n    apache_load{application=~\"$application\", environment=~\"$env\",instance=~\"$host:$port\"}\r\n    , \"shortname\", \"$short\", \"instance\", \"^(?P<short>[^.]+).*\")\r\n)",
     "legendFormat": "{{ shortname }} {{ interval }}"
    }
   ]
  }
 ]
}